### ISSUE TITLE
Error: Cannot find module 'react/lib/DOMProperty'

### ISSUE THREAD

**Issue by ryanscottaudio** [chromakode/react-html-email#26]
```
Error: Cannot find module 'react/lib/DOMProperty'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/react-html-email/lib/injectReactEmailAttributes.js:11:20)

**Comment by mfeuermann** [comment]
Same issue here...

**Comment by chromakode** [comment]
Fixed in v1.1.3 :+1: https://github.com/chromakode/react-html-email/pull/27

**Comment by Zaiban** [comment]
Hey. I'm still getting this error after updating to 1.1.3. Tried clearing caches and stuff but no avail. Also checked the node_modules/react-html-email/package.json and it shows 1.1.3.
```
ERROR in ./~/react-html-email/lib/injectReactEmailAttributes.js
Module not found: Error: Cannot resolve module 'react/lib/DOMProperty' in /home/esa/GitRepos/lumate-equipment-bank/node_modules/react-html-email/lib
 @ ./~/react-html-email/lib/injectReactEmailAttributes.js 18:39-71
```
